words = [
    "atoi",
    "creds",
    "cron",
    "fprint",
    "getenv",
    "gorm",
    "gorm's",
    "hmac",
    "ips",
    "liveness",
    "nosniff",
    "sslmode",
    "submatch",
    "subrouter",
    "syncsvc",
    "unquarantine",
    "xss",
    "yar",
    "yara",
]
